### ISSUE TITLE
readme has a minor error

### ISSUE THREAD

**Issue by eddieduro** [balinterdi/ember-cli-star-rating#11]
`{{#star-rating item=song rating=song.rating on-click=(action "updateRating")  as |stars set|}}
  {{#each stars as |star|}}
    <a {{action set star.rating}}>
      {{if star.full}}*{{else}}_{{/if}}
    </a>
  {{/each}}
{{/star-rating}`

the closing star-rating hbs tag is missing its last '}'

Just incase anyone tries to copy and paste this to sample the code.

**Comment by balinterdi** [comment]
Thank you, Edward.

**Comment by eddieduro** [comment]
@balinterdi yeah no problem!
