### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by JaxonWright** [balinterdi/ember-cli-star-rating#14]
you wrote "emtyClassNames" and "fullClassNames" but they should not be plural

**Comment by balinterdi** [comment]
I think they are plural everywhere, check out the code [here](https://github.com/balinterdi/ember-cli-star-rating/blob/master/addon/components/star-rating.js#L15-L16)

**Comment by JaxonWright** [comment]
that is strange, because it was not working until I used it without the s at the end. I ended up not needing to use them in the end anyway, though.

**Comment by JaxonWright** [comment]
Oh, I think I know what happened. I was trying to use font-awesome, but I didn't have it included. Therefore when I removed the 's' it ignored it and used the regular icons. My bad
