### ISSUE TITLE
Release a version for Ember >= 1.13

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/ember-cli-star-rating#2]
The distinguishing features would be using `hasBlock` in the template (to avoid deprecations in the consuming app) and using closure actions instead of bubbling ones (because they are better).

**Comment by knownasilya** [comment]
Is this done?

**Comment by balinterdi** [comment]
The `hasBlock` stuff is not yet there so you'll get a deprecation warning for Ember >= 2.0 , but I realized I can support both closure and old-style actions without needing to relese two versions. [Here is the relevant code bit](https://github.com/balinterdi/ember-cli-star-rating/blob/master/addon/components/star-rating.js#L33-L43).

**Comment by balinterdi** [comment]
Actually, this is already done in [version 0.2.0](https://github.com/balinterdi/ember-cli-star-rating/releases/tag/v0.2.0).
