### ISSUE TITLE
Introduce `star-rating-star` sub-component

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/ember-cli-star-rating#7]
The `action` helper cannot pass keyword arguments to the function that handles the action:

```hbs
<div class="list-group songs">
  {{#each sortedSongs as |song|}}
    <div class="list-group-item song">
      {{capitalize-words song.title}}
      {{#star-rating item=song rating=song.rating as |stars|}}
        {{#each stars as |star|}}
          <span class="star-rating fa
                {{if star.full 'fa-star' 'fa-star-o'}}"
                {{action "updateRating" item=song rating=star.rating}}> <!-- <= Cannot write this -->
          </span>
        {{/each}}
      {{/star-rating}}
    </div>
  {{/each}}
</div>
```

That means the `updateRating` action handler needs to be modified to take positional parameters (as opposed to taking the `item` and `rating` hash keys). The fact that the action handler needs to change in order to allow the block form to be used points to a flaw in the component's design. One way to fix that
is to have a subcomponent, `star-rating-star` and it would have the `on-click` action handler which would call the action passed to the top-level `star-rating` component.

**Comment by knownasilya** [comment]
Why not do `{{yield starts (action 'set')}}` which could be used like:

```hbs
{{#star-rating item=song rating=song.rating as |stars set|}}
  {{#each stars as |star|}}
    <a {{action set star.rating}}><i class="fa fa-star"></i></a>
  {{/each}}
{{/star-rating}}
```

**Comment by balinterdi** [comment]
That's a fantastic idea and something I haven't thought of!

In the `set` action handler of the component I could then transform the (positional) arguments into (named) parameters and the "outside" action handler (passed in to the component) need not change at all. Actually, the `set` action handler already does the conversion as it currently stands.

Thank you, I'm going to do just that.

**Comment by balinterdi** [comment]
Just cut a new release: https://github.com/balinterdi/ember-cli-star-rating/releases/tag/v0.3.0

**Comment by knownasilya** [comment]
Did you forget to document this?

**Comment by balinterdi** [comment]
I did, thank you for pointing it out. I've now updated the relevant section in the readme.
